### ISSUE TITLE
Moving to vue-loader as vueify is deprecated

### ISSUE THREAD

**Issue by zllovesuki** [zllovesuki/slugsurvival#22]
For some reasons this flew under my radar.. Next on the to-do list.

**Comment by eankeen** [comment]
Hey, is there an update on this? This sounds like something I could possibly help out with, if you are looking for contributors. I assume we would be migrating from a browserify based build system to webpack?

**Comment by zllovesuki** [comment]
My code is pretty spaghetti at the moment... maybe refactor it before moving to webpack lmao

**Comment by eankeen** [comment]
even if it's a bit messy, i'm close to a working configuration, probably with minimal refactoring. i have a fork [here](https://github.com/eankeen/slugsurvival), and can be checked with just the `dev2` script. however, it made the browserify build break due to [this](https://github.com/eankeen/slugsurvival/commit/baf296f95d1769dd318b80b625f636f7a63f8ed3) commit because browserify and webpack resolve commonjs imports from es modules a bit differently. for some reason, the site doesnt seem to be getting past a loading spinner, possibly due to incorrect configuration (i have to look into it more). were you looking to keep the browserify build process or migrate to webpack completely?

**Comment by zllovesuki** [comment]
Moving to webpack should be the goal. What errors did you encounter in the console? It has some dependency from `config.js`. Namely, it is taking data from Andromeda.

**Comment by zllovesuki** [comment]
See `src/views/index.vue`. The `mounted` event is not is getting some love. I should take a look at it later. Working on midterm project atm

**Comment by eankeen** [comment]
oye! so i was able to get everything to build and work, for the most part. :smile: on my side, i just need to fix some font errors, properly create builds for production, and maybe work on the webpack development server. the most significant part of the migration was ensuring that we access the `.default` property of Vue modules that we `require`. i'll probably get that done in a few days

**Comment by eankeen** [comment]
i saw that you had some babel 6 dependencies in your `package.json`. i removed them since they didn't seem to be used, but were you looking to add babel? unlike browserify, webpack resolves es module syntax away, so we wouldn't need it for that reason.

**Comment by zllovesuki** [comment]
I’m not sure why they were in there in the first place, probably polluted the config by npm install in the wrong folder, just like how you forget to activate your virtualenv before pip install 😤

Anyway, thanks for working on this long overdue to-do. I shall check out your code when I’m close to done with my current project on hand.

**Comment by eankeen** [comment]
i just opened a pr so you can review my code. glad i could help out :smiley:
